services:

  php:
    build:
      context: .
      dockerfile: .docker/php.Dockerfile
      args:
        USER: ${USER}
    environment:
      POSTGRES_HOST: pgpool
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - postgres
    volumes:
      - .:/var/www/
      - .docker/php.ini:/usr/local/etc/php/php.ini
      - .docker/fpm.conf:/usr/local/etc/php-fpm.d/www.conf

  nginx:
    image: nginxinc/nginx-unprivileged:1.22-alpine
    volumes:
      - .:/var/www
      - .docker/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8081:8080"
    depends_on:
      - php

  postgres:
    image: postgres:15-bullseye
    volumes:
      - .docker/postgres.conf:/var/lib/postgresql/data/postgresql.conf
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
      - POSTGRES_DB=docker
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
      - PGDATA=/pg

  pgpool:
    image: bitnami/pgpool:latest
    ports:
      - "5433:5432"
    environment:
      - PGPOOL_BACKEND_NODES=0:postgres:5432
      - PGPOOL_SR_CHECK_USER=docker
      - PGPOOL_SR_CHECK_PASSWORD=docker
      - PGPOOL_ENABLE_LDAP=no
      - PGPOOL_POSTGRES_USERNAME=docker
      - PGPOOL_POSTGRES_PASSWORD=docker
      - PGPOOL_ADMIN_USERNAME=admin
      - PGPOOL_ADMIN_PASSWORD=adminpassword
