services:

  php:
    build:
      context: .
      dockerfile: .docker/php.Dockerfile
      args:
        USER: ${USER}
    environment:
      POSTGRES_HOST: postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - postgres
    volumes:
      - .:/var/www/
      - .docker/fpm.conf:/usr/local/etc/php-fpm.d/www.conf

  nginx:
    image: nginxinc/nginx-unprivileged:1.22-alpine
    volumes:
      - .:/var/www
      - .docker/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8081:8080"
    depends_on:
      - php

  postgres:
    image: postgres:15-bullseye
    volumes:
      - .docker/postgres.conf:/etc/postgresql/postgresql.conf
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
      - POSTGRES_DB=docker
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
